// Package gemini provides Google Gemini CLI agent integration.
// Gemini: Google's multimodal AI with code generation capabilities.
package gemini

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// Gemini provides Google Gemini integration
type Gemini struct {
	*base.BaseIntegration
	config *Config
}

// Config holds Gemini configuration
type Config struct {
	base.BaseConfig
	APIKey          string
	Model           string
	MaxTokens       int
	Temperature     float64
	Multimodal      bool
}

// New creates a new Gemini integration
func New() *Gemini {
	info := agents.AgentInfo{
		Type:        agents.TypeGeminiCLI,
		Name:        "Gemini CLI",
		Description: "Google's multimodal AI coding assistant",
		Vendor:      "Google",
		Version:     "1.0.0",
		Capabilities: []string{
			"multimodal",
			"code_generation",
			"code_explanation",
			"chat",
			"image_understanding",
			"long_context",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &Gemini{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			Model:       "gemini-2.5-pro",
			MaxTokens:   8192,
			Temperature: 0.7,
			Multimodal:  true,
		},
	}
}

// Initialize initializes Gemini
func (g *Gemini) Initialize(ctx context.Context, config interface{}) error {
	if err := g.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		g.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (g *Gemini) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !g.IsStarted() {
		if err := g.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "chat":
		return g.chat(ctx, params)
	case "generate":
		return g.generate(ctx, params)
	case "explain":
		return g.explain(ctx, params)
	case "analyze_image":
		return g.analyzeImage(ctx, params)
	case "review":
		return g.review(ctx, params)
	case "status":
		return g.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// chat performs chat
func (g *Gemini) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	return map[string]interface{}{
		"message":  message,
		"response": fmt.Sprintf("Gemini: %s", message),
		"model":    g.config.Model,
	}, nil
}

// generate generates code
func (g *Gemini) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	language, _ := params["language"].(string)
	
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	if language == "" {
		language = "go"
	}
	
	code := fmt.Sprintf("// Generated by Gemini\n// Prompt: %s\n// Model: %s\n\nfunc generated() {\n    // Implementation\n}\n", prompt, g.config.Model)
	
	return map[string]interface{}{
		"prompt":   prompt,
		"language": language,
		"code":     code,
		"model":    g.config.Model,
	}, nil
}

// explain explains code
func (g *Gemini) explain(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	if code == "" {
		return nil, fmt.Errorf("code required")
	}
	
	return map[string]interface{}{
		"code":        code,
		"explanation": fmt.Sprintf("Explanation by %s:\n\nThis code...", g.config.Model),
		"model":       g.config.Model,
	}, nil
}

// analyzeImage analyzes an image
func (g *Gemini) analyzeImage(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	imagePath, _ := params["image_path"].(string)
	if imagePath == "" {
		return nil, fmt.Errorf("image_path required")
	}
	
	if !g.config.Multimodal {
		return nil, fmt.Errorf("multimodal mode not enabled")
	}
	
	return map[string]interface{}{
		"image_path": imagePath,
		"analysis":   "Image analysis by Gemini",
		"model":      g.config.Model,
	}, nil
}

// review reviews code
func (g *Gemini) review(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	if code == "" {
		return nil, fmt.Errorf("code required")
	}
	
	return map[string]interface{}{
		"code":   code,
		"review": "Code review by Gemini",
		"issues": []map[string]interface{}{
			{"type": "suggestion", "message": "Consider improvements"},
		},
	}, nil
}

// status returns status
func (g *Gemini) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available":   g.IsAvailable(),
		"model":       g.config.Model,
		"multimodal":  g.config.Multimodal,
		"max_tokens":  g.config.MaxTokens,
	}, nil
}

// IsAvailable checks availability
func (g *Gemini) IsAvailable() bool {
	return g.config.APIKey != ""
}

var _ agents.AgentIntegration = (*Gemini)(nil)