// Package jetbrainsai provides JetBrains AI Assistant integration.
// JetBrains AI: AI coding assistant integrated into JetBrains IDEs.
package jetbrainsai

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// JetBrainsAI provides JetBrains AI integration
type JetBrainsAI struct {
	*base.BaseIntegration
	config *Config
}

// Config holds JetBrains AI configuration
type Config struct {
	base.BaseConfig
	IDEType      string // "intellij", "pycharm", "goland", "webstorm"
	Model        string
	EnableInline bool
	EnableChat   bool
}

// New creates a new JetBrains AI integration
func New() *JetBrainsAI {
	info := agents.AgentInfo{
		Type:        agents.TypeJetBrainsAI,
		Name:        "JetBrains AI",
		Description: "AI assistant for JetBrains IDEs",
		Vendor:      "JetBrains",
		Version:     "1.0.0",
		Capabilities: []string{
			"ide_integration",
			"inline_completion",
			"chat",
			"code_generation",
			"code_explanation",
			"test_generation",
			"documentation",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &JetBrainsAI{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			IDEType:      "intellij",
			Model:        "claude-3-sonnet",
			EnableInline: true,
			EnableChat:   true,
		},
	}
}

// Initialize initializes JetBrains AI
func (j *JetBrainsAI) Initialize(ctx context.Context, config interface{}) error {
	if err := j.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		j.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (j *JetBrainsAI) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !j.IsStarted() {
		if err := j.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "complete":
		return j.complete(ctx, params)
	case "chat":
		return j.chat(ctx, params)
	case "generate":
		return j.generate(ctx, params)
	case "explain":
		return j.explain(ctx, params)
	case "test":
		return j.test(ctx, params)
	case "docs":
		return j.docs(ctx, params)
	case "status":
		return j.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// complete generates inline completion
func (j *JetBrainsAI) complete(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	file, _ := params["file"].(string)
	line, _ := params["line"].(int)
	column, _ := params["column"].(int)
	
	return map[string]interface{}{
		"file":       file,
		"line":       line,
		"column":     column,
		"completion": "// JetBrains AI completion",
		"ide":        j.config.IDEType,
	}, nil
}

// chat performs chat
func (j *JetBrainsAI) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	return map[string]interface{}{
		"message":  message,
		"response": fmt.Sprintf("JetBrains AI: %s", message),
		"ide":      j.config.IDEType,
	}, nil
}

// generate generates code
func (j *JetBrainsAI) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	language, _ := params["language"].(string)
	
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	if language == "" {
		language = "java"
	}
	
	code := fmt.Sprintf("// Generated by JetBrains AI\n// Prompt: %s\n", prompt)
	
	return map[string]interface{}{
		"prompt":   prompt,
		"language": language,
		"code":     code,
		"ide":      j.config.IDEType,
	}, nil
}

// explain explains code
func (j *JetBrainsAI) explain(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	if code == "" {
		return nil, fmt.Errorf("code required")
	}
	
	return map[string]interface{}{
		"code":        code,
		"explanation": "Code explanation from JetBrains AI",
	}, nil
}

// test generates tests
func (j *JetBrainsAI) test(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	if code == "" {
		return nil, fmt.Errorf("code required")
	}
	
	return map[string]interface{}{
		"code":  code,
		"tests": "// Generated tests by JetBrains AI",
	}, nil
}

// docs generates documentation
func (j *JetBrainsAI) docs(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	if code == "" {
		return nil, fmt.Errorf("code required")
	}
	
	return map[string]interface{}{
		"code": code,
		"docs": "/** Generated documentation by JetBrains AI */",
	}, nil
}

// status returns status
func (j *JetBrainsAI) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available":     j.IsAvailable(),
		"ide":           j.config.IDEType,
		"inline_enabled": j.config.EnableInline,
		"chat_enabled":   j.config.EnableChat,
	}, nil
}

// IsAvailable checks availability
func (j *JetBrainsAI) IsAvailable() bool {
	return j.config.IDEType != ""
}

var _ agents.AgentIntegration = (*JetBrainsAI)(nil)