// Package kimi provides Kimi agent integration.
// Kimi: Moonshot AI's long-context language model.
package kimi

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// Kimi provides Kimi integration
type Kimi struct {
	*base.BaseIntegration
	config *Config
}

// Config holds Kimi configuration
type Config struct {
	base.BaseConfig
	APIKey         string
	Model          string
	ContextWindow  int
	MaxTokens      int
}

// New creates a new Kimi integration
func New() *Kimi {
	info := agents.AgentInfo{
		Type:        agents.TypeKimi,
		Name:        "Kimi",
		Description: "Moonshot AI long-context model",
		Vendor:      "Moonshot AI",
		Version:     "1.0.0",
		Capabilities: []string{
			"long_context",
			"code_generation",
			"chat",
			"document_analysis",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &Kimi{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			Model:         "kimi-k2",
			ContextWindow: 2000000,
			MaxTokens:     8192,
		},
	}
}

// Initialize initializes Kimi
func (k *Kimi) Initialize(ctx context.Context, config interface{}) error {
	if err := k.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		k.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (k *Kimi) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !k.IsStarted() {
		if err := k.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "chat":
		return k.chat(ctx, params)
	case "generate":
		return k.generate(ctx, params)
	case "analyze":
		return k.analyze(ctx, params)
	case "status":
		return k.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// chat performs chat
func (k *Kimi) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	return map[string]interface{}{
		"message":  message,
		"response": fmt.Sprintf("Kimi: %s", message),
		"model":    k.config.Model,
	}, nil
}

// generate generates code
func (k *Kimi) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	return map[string]interface{}{
		"prompt": prompt,
		"code":   fmt.Sprintf("// Generated by Kimi\n// %s", prompt),
		"model":  k.config.Model,
	}, nil
}

// analyze analyzes a document
func (k *Kimi) analyze(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	document, _ := params["document"].(string)
	if document == "" {
		return nil, fmt.Errorf("document required")
	}
	
	return map[string]interface{}{
		"document": document,
		"analysis": "Document analysis by Kimi",
		"model":    k.config.Model,
	}, nil
}

// status returns status
func (k *Kimi) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available":      k.IsAvailable(),
		"model":          k.config.Model,
		"context_window": k.config.ContextWindow,
	}, nil
}

// IsAvailable checks availability
func (k *Kimi) IsAvailable() bool {
	return k.config.APIKey != ""
}

var _ agents.AgentIntegration = (*Kimi)(nil)