// Package deepseekcli provides DeepSeek CLI agent integration.
// DeepSeek CLI: Command-line interface for DeepSeek models.
package deepseekcli

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// DeepSeekCLI provides DeepSeek CLI integration
type DeepSeekCLI struct {
	*base.BaseIntegration
	config *Config
}

// Config holds configuration
type Config struct {
	base.BaseConfig
	APIKey      string
	Model       string
	MaxTokens   int
}

// New creates a new DeepSeek CLI integration
func New() *DeepSeekCLI {
	info := agents.AgentInfo{
		Type:        agents.TypeDeepseekCLI,
		Name:        "DeepSeek CLI",
		Description: "CLI for DeepSeek models",
		Vendor:      "DeepSeek",
		Version:     "1.0.0",
		Capabilities: []string{
			"code_generation",
			"chat",
			"completion",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &DeepSeekCLI{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			Model:     "deepseek-chat",
			MaxTokens: 4096,
		},
	}
}

// Initialize initializes DeepSeek CLI
func (d *DeepSeekCLI) Initialize(ctx context.Context, config interface{}) error {
	if err := d.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		d.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (d *DeepSeekCLI) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !d.IsStarted() {
		if err := d.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "chat":
		return d.chat(ctx, params)
	case "generate":
		return d.generate(ctx, params)
	case "status":
		return d.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// chat performs chat
func (d *DeepSeekCLI) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	return map[string]interface{}{
		"message":  message,
		"response": fmt.Sprintf("DeepSeek: %s", message),
		"model":    d.config.Model,
	}, nil
}

// generate generates code
func (d *DeepSeekCLI) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	return map[string]interface{}{
		"prompt": prompt,
		"code":   fmt.Sprintf("// Generated by DeepSeek CLI\n// %s", prompt),
		"model":  d.config.Model,
	}, nil
}

// status returns status
func (d *DeepSeekCLI) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available":  d.IsAvailable(),
		"model":      d.config.Model,
		"max_tokens": d.config.MaxTokens,
	}, nil
}

// IsAvailable checks availability
func (d *DeepSeekCLI) IsAvailable() bool {
	return d.config.APIKey != ""
}

var _ agents.AgentIntegration = (*DeepSeekCLI)(nil)