linters:
  disable-all: true
  enable:
    - errcheck
    - govet

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

run:
  go: '1.24'
  timeout: 5m
  modules-download-mode: mod
  skip-dirs:
    - cli_agents
    - MCP
    - MCP-Servers

issues:
  exclude-rules:
    - path: .*_test\.go$
      linters:
        - errcheck
    - path: cli_agents/
      linters:
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - typecheck
    - path: MCP/submodules/
      linters:
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - typecheck
    - path: MCP-Servers/
      linters:
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - typecheck
    - path: vendor/
      linters:
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - typecheck

severity:
  default: warning
