# Gosec configuration file for HelixAgent
# Suppress false positives for jitter calculations in retry backoff

# Global settings
global:
  nosec: true  # Enable nosec comments

# Rule-specific exclusions
rules:
  G404:  # Weak random number generator
    nosec: true

# File-specific exclusions
exclude:
  # Suppress G404 for jitter calculations in LLM providers
  - paths:
      - internal/llm/providers/xai/xai.go
    line: 571
    rules:
      - G404
  - paths:
      - internal/llm/providers/together/together.go
    line: 560
    rules:
      - G404
  - paths:
      - internal/llm/providers/replicate/replicate.go
    line: 508
    rules:
      - G404
  - paths:
      - internal/llm/providers/perplexity/perplexity.go
    line: 502
    rules:
      - G404
  - paths:
      - internal/llm/providers/openai/openai.go
    line: 511
    rules:
      - G404
  - paths:
      - internal/llm/providers/huggingface/huggingface.go
    line: 634
    rules:
      - G404
  - paths:
      - internal/llm/providers/groq/groq.go
    line: 597
    rules:
      - G404
  - paths:
      - internal/llm/providers/fireworks/fireworks.go
    line: 559
    rules:
      - G404
  - paths:
      - internal/llm/providers/cohere/cohere.go
    line: 626
    rules:
      - G404
  - paths:
      - internal/llm/providers/anthropic/anthropic.go
    line: 546
    rules:
      - G404
  - paths:
      - internal/llm/providers/ai21/ai21.go
    line: 540
    rules:
      - G404
  # Additional LLM providers with G404 (may be lower severity)
  - paths:
      - internal/llm/providers/zai/zai.go
    line: 691
    rules:
      - G404
  - paths:
      - internal/llm/providers/zen/zen.go
    line: 922
    rules:
      - G404
  - paths:
      - internal/llm/providers/claude/claude.go
    line: 675
    rules:
      - G404
  - paths:
      - internal/llm/providers/qwen/qwen.go
    line: 892
    rules:
      - G404
  - paths:
      - internal/llm/providers/mistral/mistral.go
    line: 658
    rules:
      - G404
  - paths:
      - internal/llm/providers/deepseek/deepseek.go
    line: 548
    rules:
      - G404
  - paths:
      - internal/llm/providers/cerebras/cerebras.go
    line: 584
    rules:
      - G404
  - paths:
      - internal/llm/providers/openrouter/openrouter.go
    line: 324
    rules:
      - G404
  - paths:
      - internal/llm/providers/ollama/ollama.go
    line: 430
    rules:
      - G404
  - paths:
      - internal/llm/providers/gemini/gemini.go
    line: 735
    rules:
      - G404
  - paths:
      - internal/formatters/executor.go
    line: 228
    rules:
      - G115
  - paths:
      - internal/formatters/executor.go
    line: 221
    rules:
      - G115

# Exclude directories
exclude-dirs:
  - vendor
  - testdata
  - reports
  - bin
  - docs

# Include rules (scan everything)
include:
  - "*"