# YAMLLint configuration
# https://yamllint.readthedocs.io/

extends: default

rules:
  # Line length - allow longer lines for readability
  line-length:
    max: 150
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true

  # Truthy values - allow various boolean representations
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Comments
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  # Document markers
  document-start: disable
  document-end: disable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Key duplicates
  key-duplicates: enable

  # New line at end of file
  new-line-at-end-of-file: enable

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Octal values
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

  # Quoted strings
  quoted-strings: disable

# Ignore patterns
ignore: |
  cli_agents/
  MCP/
  vendor/
  .git/
  node_modules/
