// Package junie provides Junie agent integration.
// Junie: JetBrains AI coding assistant.
package junie

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// Junie provides Junie integration
type Junie struct {
	*base.BaseIntegration
	config *Config
}

// Config holds configuration
type Config struct {
	base.BaseConfig
	IDE string
}

// New creates a new Junie integration
func New() *Junie {
	info := agents.AgentInfo{
		Type:        agents.TypeJunie,
		Name:        "Junie",
		Description: "JetBrains AI assistant",
		Vendor:      "JetBrains",
		Version:     "1.0.0",
		Capabilities: []string{
			"ide_integration",
			"code_completion",
			"code_generation",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &Junie{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			IDE: "intellij",
		},
	}
}

// Initialize initializes Junie
func (j *Junie) Initialize(ctx context.Context, config interface{}) error {
	if err := j.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		j.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (j *Junie) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !j.IsStarted() {
		if err := j.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "complete":
		return j.complete(ctx, params)
	case "generate":
		return j.generate(ctx, params)
	case "status":
		return j.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// complete generates completion
func (j *Junie) complete(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	
	return map[string]interface{}{
		"code":       code,
		"completion": "// Junie completion",
	}, nil
}

// generate generates code
func (j *Junie) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	return map[string]interface{}{
		"prompt": prompt,
		"code":   fmt.Sprintf("// Generated by Junie\n// %s", prompt),
	}, nil
}

// status returns status
func (j *Junie) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available": j.IsAvailable(),
		"ide":       j.config.IDE,
	}, nil
}

// IsAvailable checks availability
func (j *Junie) IsAvailable() bool {
	return true
}

var _ agents.AgentIntegration = (*Junie)(nil)