// Package hunyuan provides Hunyuan agent integration.
// Hunyuan: Tencent's multimodal AI model.
package hunyuan

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// Hunyuan provides Hunyuan integration
type Hunyuan struct {
	*base.BaseIntegration
	config *Config
}

// Config holds Hunyuan configuration
type Config struct {
	base.BaseConfig
	APIKey      string
	SecretID    string
	SecretKey   string
	Region      string
	Model       string
}

// New creates a new Hunyuan integration
func New() *Hunyuan {
	info := agents.AgentInfo{
		Type:        agents.TypeHunyuan,
		Name:        "Hunyuan",
		Description: "Tencent's multimodal AI",
		Vendor:      "Tencent",
		Version:     "1.0.0",
		Capabilities: []string{
			"multimodal",
			"code_generation",
			"chat",
			"image_generation",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &Hunyuan{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			Region: "ap-guangzhou",
			Model:  "hunyuan-pro",
		},
	}
}

// Initialize initializes Hunyuan
func (h *Hunyuan) Initialize(ctx context.Context, config interface{}) error {
	if err := h.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		h.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (h *Hunyuan) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !h.IsStarted() {
		if err := h.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "chat":
		return h.chat(ctx, params)
	case "generate":
		return h.generate(ctx, params)
	case "status":
		return h.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// chat performs chat
func (h *Hunyuan) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	return map[string]interface{}{
		"message":  message,
		"response": fmt.Sprintf("Hunyuan: %s", message),
		"model":    h.config.Model,
	}, nil
}

// generate generates code
func (h *Hunyuan) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	return map[string]interface{}{
		"prompt": prompt,
		"code":   fmt.Sprintf("// Generated by Hunyuan\n// %s", prompt),
		"model":  h.config.Model,
	}, nil
}

// status returns status
func (h *Hunyuan) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available": h.IsAvailable(),
		"model":     h.config.Model,
		"region":    h.config.Region,
	}, nil
}

// IsAvailable checks availability
func (h *Hunyuan) IsAvailable() bool {
	return h.config.APIKey != "" && h.config.SecretID != ""
}

var _ agents.AgentIntegration = (*Hunyuan)(nil)