#!/bin/bash

version="bun-v1.3.5"
downloadDir=$(pwd)/download/bun/${version}
bunCmd="$downloadDir/bin/bun"

if [ ! -f "$bunCmd" ]; then
    echo Installing bun to "$bunCmd"
    bashArgs=()
    if [ "$version" != "latest" ]; then
        bashArgs=(-s "$version")
    fi
    curl -fsSL https://bun.sh/install | BUN_INSTALL="$downloadDir" bash "${bashArgs[@]}"
fi

exec "$bunCmd" "$@"