// Package mistralcode provides Mistral Code agent integration.
// Mistral Code: AI coding assistant by Mistral AI.
package mistralcode

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// MistralCode provides Mistral Code integration
type MistralCode struct {
	*base.BaseIntegration
	config *Config
}

// Config holds configuration
type Config struct {
	base.BaseConfig
	APIKey string
	Model  string
}

// New creates a new Mistral Code integration
func New() *MistralCode {
	info := agents.AgentInfo{
		Type:        agents.TypeMistralCode,
		Name:        "Mistral Code",
		Description: "Mistral AI coding assistant",
		Vendor:      "Mistral AI",
		Version:     "1.0.0",
		Capabilities: []string{
			"code_generation",
			"code_completion",
			"chat",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &MistralCode{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			Model: "codestral-latest",
		},
	}
}

// Initialize initializes Mistral Code
func (m *MistralCode) Initialize(ctx context.Context, config interface{}) error {
	if err := m.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		m.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (m *MistralCode) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !m.IsStarted() {
		if err := m.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "complete":
		return m.complete(ctx, params)
	case "generate":
		return m.generate(ctx, params)
	case "chat":
		return m.chat(ctx, params)
	case "status":
		return m.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// complete generates completion
func (m *MistralCode) complete(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prefix, _ := params["prefix"].(string)
	
	return map[string]interface{}{
		"prefix":     prefix,
		"completion": "// Mistral completion",
		"model":      m.config.Model,
	}, nil
}

// generate generates code
func (m *MistralCode) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	return map[string]interface{}{
		"prompt": prompt,
		"code":   fmt.Sprintf("// Generated by Mistral\n// %s", prompt),
		"model":  m.config.Model,
	}, nil
}

// chat performs chat
func (m *MistralCode) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	return map[string]interface{}{
		"message":  message,
		"response": fmt.Sprintf("Mistral: %s", message),
		"model":    m.config.Model,
	}, nil
}

// status returns status
func (m *MistralCode) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available": m.IsAvailable(),
		"model":     m.config.Model,
	}, nil
}

// IsAvailable checks availability
func (m *MistralCode) IsAvailable() bool {
	return m.config.APIKey != ""
}

var _ agents.AgentIntegration = (*MistralCode)(nil)