package services

import (
	"context"
	"os"
	"path/filepath"
	"sort"
	"testing"
	"time"

	"dev.helix.agent/internal/verifier"
	"github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestVerificationReportGenerator_GenerateReport(t *testing.T) {
	log := logrus.New()
	log.SetLevel(logrus.DebugLevel)

	tempDir := t.TempDir()
	reportPath := filepath.Join(tempDir, "test_report.md")

	generator := &VerificationReportGenerator{
		log:        log,
		reportPath: reportPath,
	}

	t.Run("generates placeholder report when verificationSvc is nil", func(t *testing.T) {
		generator.verificationSvc = nil
		path, err := generator.GenerateReport(context.Background())
		assert.NoError(t, err, "nil verificationSvc should generate placeholder, not error")
		assert.Equal(t, reportPath, path)
	})
}

func TestVerificationReportGenerator_FormatReport(t *testing.T) {
	log := logrus.New()
	generator := &VerificationReportGenerator{log: log}

	entries := []ModelReportEntry{
		{
			ModelID:            "claude-3-5-sonnet",
			ProviderName:       "claude",
			OverallScore:       9.5,
			Status:             "verified",
			Verified:           true,
			CodeVisible:        true,
			VerificationTimeMs: 1500,
			Tests:              map[string]bool{"test1": true, "test2": true},
			CompletedAt:        time.Now(),
		},
		{
			ModelID:            "gpt-4",
			ProviderName:       "openai",
			OverallScore:       8.8,
			Status:             "verified",
			Verified:           true,
			CodeVisible:        true,
			VerificationTimeMs: 2000,
			Tests:              map[string]bool{"test1": true, "test2": false},
			CompletedAt:        time.Now(),
		},
		{
			ModelID:            "slow-model",
			ProviderName:       "test",
			OverallScore:       3.5,
			Status:             "failed",
			Verified:           false,
			CodeVisible:        false,
			VerificationTimeMs: 35000,
			Tests:              map[string]bool{"test1": false, "test2": false},
			CompletedAt:        time.Now(),
		},
	}

	reportContent := generator.formatReport(entries)

	assert.Contains(t, reportContent, "# Provider Verification Report")
	assert.Contains(t, reportContent, "**Total models:** 3")
	assert.Contains(t, reportContent, "**Healthy:** 2 | **Failed:** 1")
	assert.Contains(t, reportContent, "## 📊 Model Rankings (Best to Worst)")
	assert.Contains(t, reportContent, "claude-3-5-sonnet")
	assert.Contains(t, reportContent, "gpt-4")
	assert.Contains(t, reportContent, "slow-model")
	assert.Contains(t, reportContent, "✅")
	assert.Contains(t, reportContent, "❌")
	assert.Contains(t, reportContent, "9.50")
	assert.Contains(t, reportContent, "8.80")
	assert.Contains(t, reportContent, "3.50")
	assert.Contains(t, reportContent, "## 📋 Detailed Breakdown")
	assert.Contains(t, reportContent, "### ✅ Healthy Models")
	assert.Contains(t, reportContent, "### ❌ Failed Models")
	assert.Contains(t, reportContent, "auto-generated by HelixAgent LLMsVerifier")
}

func TestVerificationReportGenerator_InferErrorReason(t *testing.T) {
	log := logrus.New()
	generator := &VerificationReportGenerator{log: log}

	tests := []struct {
		name     string
		v        *verifier.VerificationStatus
		expected string
	}{
		{
			name: "zero score",
			v: &verifier.VerificationStatus{
				OverallScore: 0,
				Status:       "failed",
			},
			expected: "score is 0",
		},
		{
			name: "too slow",
			v: &verifier.VerificationStatus{
				OverallScore:       8.0,
				VerificationTimeMs: 35000,
				Status:             "failed",
			},
			expected: "too slow",
		},
		{
			name: "no code visible",
			v: &verifier.VerificationStatus{
				OverallScore: 8.0,
				CodeVisible:  false,
				Status:       "failed",
			},
			expected: "code visibility check failed",
		},
		{
			name: "failed tests",
			v: &verifier.VerificationStatus{
				OverallScore: 8.0,
				CodeVisible:  true,
				Tests:        map[string]bool{"test1": false, "test2": false},
				Status:       "failed",
			},
			expected: "Failed tests:",
		},
		{
			name: "unknown reason",
			v: &verifier.VerificationStatus{
				OverallScore: 8.0,
				CodeVisible:  true,
				Tests:        map[string]bool{"test1": true},
				Status:       "failed",
			},
			expected: "reason unknown",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			reason := generator.inferErrorReason(tt.v)
			assert.Contains(t, reason, tt.expected)
		})
	}
}

func TestVerificationReportGenerator_SaveReport(t *testing.T) {
	log := logrus.New()
	tempDir := t.TempDir()
	reportPath := filepath.Join(tempDir, "reports", "test_report.md")

	generator := &VerificationReportGenerator{
		log:        log,
		reportPath: reportPath,
	}

	content := "# Test Report\n\nThis is a test report."

	err := generator.saveReport(content)
	require.NoError(t, err)

	// Verify file was created
	assert.FileExists(t, reportPath)

	// Verify content
	data, err := os.ReadFile(reportPath)
	require.NoError(t, err)
	assert.Equal(t, content, string(data))
}

func TestVerificationReportGenerator_GetReportPath(t *testing.T) {
	generator := &VerificationReportGenerator{
		reportPath: "/tmp/test_report.md",
	}

	assert.Equal(t, "/tmp/test_report.md", generator.GetReportPath())
}

func TestVerificationReportGenerator_GetReportURL(t *testing.T) {
	generator := &VerificationReportGenerator{
		reportPath: "/tmp/test_report.md",
	}

	assert.Equal(t, "file:///tmp/test_report.md", generator.GetReportURL())
}

func TestVerificationReportGenerator_SortedByScore(t *testing.T) {
	log := logrus.New()
	generator := &VerificationReportGenerator{log: log}

	entries := []ModelReportEntry{
		{ModelID: "model-1", OverallScore: 5.5, Status: "verified"},
		{ModelID: "model-2", OverallScore: 9.5, Status: "verified"},
		{ModelID: "model-3", OverallScore: 7.5, Status: "failed"},
		{ModelID: "model-4", OverallScore: 8.8, Status: "verified"},
		{ModelID: "model-5", OverallScore: 3.2, Status: "failed"},
	}

	// Sort entries as GenerateReport does before calling formatReport
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].OverallScore > entries[j].OverallScore
	})

	reportContent := generator.formatReport(entries)

	// Verify models are listed in descending order by score
	// model-2 (9.5) should come before model-4 (8.8), etc.
	idx1 := findModelIndex(reportContent, "model-2")
	idx2 := findModelIndex(reportContent, "model-4")
	idx3 := findModelIndex(reportContent, "model-3")
	idx4 := findModelIndex(reportContent, "model-1")
	idx5 := findModelIndex(reportContent, "model-5")

	assert.Less(t, idx1, idx2, "model-2 (9.5) should appear before model-4 (8.8)")
	assert.Less(t, idx2, idx3, "model-4 (8.8) should appear before model-3 (7.5)")
	assert.Less(t, idx3, idx4, "model-3 (7.5) should appear before model-1 (5.5)")
	assert.Less(t, idx4, idx5, "model-1 (5.5) should appear before model-5 (3.2)")
}

func findModelIndex(content, modelID string) int {
	idx := 0
	for i := 0; i < len(content); i++ {
		if i+len(modelID) <= len(content) && content[i:i+len(modelID)] == modelID {
			idx = i
			break
		}
	}
	return idx
}
