// Package qwencode provides Qwen Code agent integration.
// Qwen Code: Alibaba's AI coding assistant.
package qwencode

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// QwenCode provides Qwen Code integration
type QwenCode struct {
	*base.BaseIntegration
	config *Config
}

// Config holds configuration
type Config struct {
	base.BaseConfig
	APIKey string
	Model  string
}

// New creates a new Qwen Code integration
func New() *QwenCode {
	info := agents.AgentInfo{
		Type:        agents.TypeQwenCode,
		Name:        "Qwen Code",
		Description: "Alibaba AI coding assistant",
		Vendor:      "Alibaba",
		Version:     "1.0.0",
		Capabilities: []string{
			"code_generation",
			"code_completion",
			"chat",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &QwenCode{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			Model: "qwen-coder-plus",
		},
	}
}

// Initialize initializes Qwen Code
func (q *QwenCode) Initialize(ctx context.Context, config interface{}) error {
	if err := q.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		q.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (q *QwenCode) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !q.IsStarted() {
		if err := q.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "complete":
		return q.complete(ctx, params)
	case "generate":
		return q.generate(ctx, params)
	case "chat":
		return q.chat(ctx, params)
	case "status":
		return q.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// complete generates completion
func (q *QwenCode) complete(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prefix, _ := params["prefix"].(string)
	
	return map[string]interface{}{
		"prefix":     prefix,
		"completion": "// Qwen completion",
		"model":      q.config.Model,
	}, nil
}

// generate generates code
func (q *QwenCode) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	return map[string]interface{}{
		"prompt": prompt,
		"code":   fmt.Sprintf("// Generated by Qwen\n// %s", prompt),
		"model":  q.config.Model,
	}, nil
}

// chat performs chat
func (q *QwenCode) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	return map[string]interface{}{
		"message":  message,
		"response": fmt.Sprintf("Qwen: %s", message),
		"model":    q.config.Model,
	}, nil
}

// status returns status
func (q *QwenCode) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available": q.IsAvailable(),
		"model":     q.config.Model,
	}, nil
}

// IsAvailable checks availability
func (q *QwenCode) IsAvailable() bool {
	return q.config.APIKey != ""
}

var _ agents.AgentIntegration = (*QwenCode)(nil)