// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: specs/001-super-agent/contracts/llm-facade.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt         string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Messages       []*Message             `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	ModelParams    *ModelParameters       `protobuf:"bytes,5,opt,name=model_params,json=modelParams,proto3" json:"model_params,omitempty"`
	EnsembleConfig *EnsembleConfig        `protobuf:"bytes,6,opt,name=ensemble_config,json=ensembleConfig,proto3" json:"ensemble_config,omitempty"`
	MemoryEnhanced bool                   `protobuf:"varint,7,opt,name=memory_enhanced,json=memoryEnhanced,proto3" json:"memory_enhanced,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestType    string                 `protobuf:"bytes,9,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"` // code_generation, reasoning, tool_use
	Priority       int32                  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{0}
}

func (x *CompletionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompletionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompletionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CompletionRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompletionRequest) GetModelParams() *ModelParameters {
	if x != nil {
		return x.ModelParams
	}
	return nil
}

func (x *CompletionRequest) GetEnsembleConfig() *EnsembleConfig {
	if x != nil {
		return x.EnsembleConfig
	}
	return nil
}

func (x *CompletionRequest) GetMemoryEnhanced() bool {
	if x != nil {
		return x.MemoryEnhanced
	}
	return false
}

func (x *CompletionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CompletionRequest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *CompletionRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CompletionRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CompletionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResponseId       string                 `protobuf:"bytes,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Content          string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Confidence       float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	TokensUsed       int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	ResponseTimeMs   int64                  `protobuf:"varint,6,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	ProviderName     string                 `protobuf:"bytes,7,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	FinishReason     string                 `protobuf:"bytes,8,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Selected         bool                   `protobuf:"varint,9,opt,name=selected,proto3" json:"selected,omitempty"`
	SelectionScore   float64                `protobuf:"fixed64,10,opt,name=selection_score,json=selectionScore,proto3" json:"selection_score,omitempty"`
	MemorySources    []*MemorySource        `protobuf:"bytes,11,rep,name=memory_sources,json=memorySources,proto3" json:"memory_sources,omitempty"`
	ProviderMetadata *structpb.Value        `protobuf:"bytes,12,opt,name=provider_metadata,json=providerMetadata,proto3" json:"provider_metadata,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionResponse) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *CompletionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompletionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompletionResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CompletionResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *CompletionResponse) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *CompletionResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *CompletionResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *CompletionResponse) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *CompletionResponse) GetSelectionScore() float64 {
	if x != nil {
		return x.SelectionScore
	}
	return 0
}

func (x *CompletionResponse) GetMemorySources() []*MemorySource {
	if x != nil {
		return x.MemorySources
	}
	return nil
}

func (x *CompletionResponse) GetProviderMetadata() *structpb.Value {
	if x != nil {
		return x.ProviderMetadata
	}
	return nil
}

func (x *CompletionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Messages       []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	ModelParams    *ModelParameters       `protobuf:"bytes,3,opt,name=model_params,json=modelParams,proto3" json:"model_params,omitempty"`
	MemoryEnhanced bool                   `protobuf:"varint,4,opt,name=memory_enhanced,json=memoryEnhanced,proto3" json:"memory_enhanced,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetModelParams() *ModelParameters {
	if x != nil {
		return x.ModelParams
	}
	return nil
}

func (x *ChatRequest) GetMemoryEnhanced() bool {
	if x != nil {
		return x.MemoryEnhanced
	}
	return false
}

func (x *ChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseId    string                 `protobuf:"bytes,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	ProviderName  string                 `protobuf:"bytes,5,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	IsStreaming   bool                   `protobuf:"varint,6,opt,name=is_streaming,json=isStreaming,proto3" json:"is_streaming,omitempty"`
	IsComplete    bool                   `protobuf:"varint,7,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	MemorySources []*MemorySource        `protobuf:"bytes,8,rep,name=memory_sources,json=memorySources,proto3" json:"memory_sources,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ChatResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *ChatResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ChatResponse) GetIsStreaming() bool {
	if x != nil {
		return x.IsStreaming
	}
	return false
}

func (x *ChatResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *ChatResponse) GetMemorySources() []*MemorySource {
	if x != nil {
		return x.MemorySources
	}
	return nil
}

func (x *ChatResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // system, user, assistant, tool
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                            // optional for tool messages
	ToolCalls     *structpb.Value        `protobuf:"bytes,4,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"` // for tool/function calls
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetToolCalls() *structpb.Value {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type ModelParameters struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Model            string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Temperature      float64                `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens        int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	TopP             float64                `protobuf:"fixed64,4,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	StopSequences    []string               `protobuf:"bytes,5,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	ProviderSpecific *structpb.Struct       `protobuf:"bytes,6,opt,name=provider_specific,json=providerSpecific,proto3" json:"provider_specific,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelParameters) Reset() {
	*x = ModelParameters{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelParameters) ProtoMessage() {}

func (x *ModelParameters) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelParameters.ProtoReflect.Descriptor instead.
func (*ModelParameters) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{5}
}

func (x *ModelParameters) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelParameters) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ModelParameters) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelParameters) GetTopP() float64 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *ModelParameters) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *ModelParameters) GetProviderSpecific() *structpb.Struct {
	if x != nil {
		return x.ProviderSpecific
	}
	return nil
}

type EnsembleConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Strategy            string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"` // confidence_weighted, majority_vote
	MinProviders        int32                  `protobuf:"varint,2,opt,name=min_providers,json=minProviders,proto3" json:"min_providers,omitempty"`
	ConfidenceThreshold float64                `protobuf:"fixed64,3,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	FallbackToBest      bool                   `protobuf:"varint,4,opt,name=fallback_to_best,json=fallbackToBest,proto3" json:"fallback_to_best,omitempty"`
	TimeoutSeconds      int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	PreferredProviders  []string               `protobuf:"bytes,6,rep,name=preferred_providers,json=preferredProviders,proto3" json:"preferred_providers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnsembleConfig) Reset() {
	*x = EnsembleConfig{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsembleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsembleConfig) ProtoMessage() {}

func (x *EnsembleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsembleConfig.ProtoReflect.Descriptor instead.
func (*EnsembleConfig) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{6}
}

func (x *EnsembleConfig) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *EnsembleConfig) GetMinProviders() int32 {
	if x != nil {
		return x.MinProviders
	}
	return 0
}

func (x *EnsembleConfig) GetConfidenceThreshold() float64 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

func (x *EnsembleConfig) GetFallbackToBest() bool {
	if x != nil {
		return x.FallbackToBest
	}
	return false
}

func (x *EnsembleConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *EnsembleConfig) GetPreferredProviders() []string {
	if x != nil {
		return x.PreferredProviders
	}
	return nil
}

type MemorySource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatasetName    string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	RelevanceScore float64                `protobuf:"fixed64,3,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	SourceType     string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // vector, graph, summary
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemorySource) Reset() {
	*x = MemorySource{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySource) ProtoMessage() {}

func (x *MemorySource) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySource.ProtoReflect.Descriptor instead.
func (*MemorySource) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{7}
}

func (x *MemorySource) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *MemorySource) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemorySource) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *MemorySource) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnabledOnly   bool                   `protobuf:"varint,1,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	ProviderType  string                 `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{8}
}

func (x *ListProvidersRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

func (x *ListProvidersRequest) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{9}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Weight         float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Enabled        bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	HealthStatus   string                 `protobuf:"bytes,7,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,8,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	SuccessRate    float64                `protobuf:"fixed64,9,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	Capabilities   *CapabilitiesResponse  `protobuf:"bytes,10,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	LastUpdated    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProviderInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProviderInfo) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProviderInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ProviderInfo) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *ProviderInfo) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *ProviderInfo) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ProviderInfo) GetCapabilities() *CapabilitiesResponse {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderInfo) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type AddProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProviderRequest) Reset() {
	*x = AddProviderRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProviderRequest) ProtoMessage() {}

func (x *AddProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProviderRequest.ProtoReflect.Descriptor instead.
func (*AddProviderRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{11}
}

func (x *AddProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProviderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddProviderRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AddProviderRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AddProviderRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AddProviderRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AddProviderRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderRequest) Reset() {
	*x = UpdateProviderRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRequest) ProtoMessage() {}

func (x *UpdateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProviderRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UpdateProviderRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *UpdateProviderRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateProviderRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateProviderRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateProviderRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type RemoveProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // remove even if in use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProviderRequest) Reset() {
	*x = RemoveProviderRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProviderRequest) ProtoMessage() {}

func (x *RemoveProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProviderRequest.ProtoReflect.Descriptor instead.
func (*RemoveProviderRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveProviderRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Provider      *ProviderInfo          `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderResponse) Reset() {
	*x = ProviderResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderResponse) ProtoMessage() {}

func (x *ProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderResponse.ProtoReflect.Descriptor instead.
func (*ProviderResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{14}
}

func (x *ProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProviderResponse) GetProvider() *ProviderInfo {
	if x != nil {
		return x.Provider
	}
	return nil
}

type HealthRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Detailed        bool                   `protobuf:"varint,1,opt,name=detailed,proto3" json:"detailed,omitempty"`
	CheckComponents []string               `protobuf:"bytes,2,rep,name=check_components,json=checkComponents,proto3" json:"check_components,omitempty"` // optional: database, cognee, providers
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{15}
}

func (x *HealthRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

func (x *HealthRequest) GetCheckComponents() []string {
	if x != nil {
		return x.CheckComponents
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // healthy, degraded, unhealthy
	Components    []*ComponentHealth     `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ComponentHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Details        map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{17}
}

func (x *ComponentHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ComponentHealth) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *ComponentHealth) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     string                 `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // 1h, 24h, 7d
	Metrics       []string               `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`                      // optional: request_count, response_time, error_rate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{18}
}

func (x *MetricsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *MetricsRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *structpb.Struct       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{19}
}

func (x *MetricsResponse) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *MetricsResponse) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InitialContext *structpb.Struct       `protobuf:"bytes,2,opt,name=initial_context,json=initialContext,proto3" json:"initial_context,omitempty"`
	TtlHours       int32                  `protobuf:"varint,3,opt,name=ttl_hours,json=ttlHours,proto3" json:"ttl_hours,omitempty"`
	MemoryEnabled  bool                   `protobuf:"varint,4,opt,name=memory_enabled,json=memoryEnabled,proto3" json:"memory_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{20}
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionRequest) GetInitialContext() *structpb.Struct {
	if x != nil {
		return x.InitialContext
	}
	return nil
}

func (x *CreateSessionRequest) GetTtlHours() int32 {
	if x != nil {
		return x.TtlHours
	}
	return 0
}

func (x *CreateSessionRequest) GetMemoryEnabled() bool {
	if x != nil {
		return x.MemoryEnabled
	}
	return false
}

type GetSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IncludeContext bool                   `protobuf:"varint,2,opt,name=include_context,json=includeContext,proto3" json:"include_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{21}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetIncludeContext() bool {
	if x != nil {
		return x.IncludeContext
	}
	return false
}

type TerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Graceful      bool                   `protobuf:"varint,2,opt,name=graceful,proto3" json:"graceful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionRequest) Reset() {
	*x = TerminateSessionRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionRequest) ProtoMessage() {}

func (x *TerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{22}
}

func (x *TerminateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminateSessionRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // active, expired, terminated
	RequestCount  int32                  `protobuf:"varint,5,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,8,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{23}
}

func (x *SessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionResponse) GetRequestCount() int32 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *SessionResponse) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *SessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SessionResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{24}
}

type CapabilitiesResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SupportedModels         []string               `protobuf:"bytes,1,rep,name=supported_models,json=supportedModels,proto3" json:"supported_models,omitempty"`
	SupportedFeatures       []string               `protobuf:"bytes,2,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"` // streaming, function_calling, vision, etc.
	Limits                  *ModelLimits           `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	SupportedRequestTypes   []string               `protobuf:"bytes,4,rep,name=supported_request_types,json=supportedRequestTypes,proto3" json:"supported_request_types,omitempty"`
	SupportsStreaming       bool                   `protobuf:"varint,5,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	SupportsFunctionCalling bool                   `protobuf:"varint,6,opt,name=supports_function_calling,json=supportsFunctionCalling,proto3" json:"supports_function_calling,omitempty"`
	SupportsVision          bool                   `protobuf:"varint,7,opt,name=supports_vision,json=supportsVision,proto3" json:"supports_vision,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{25}
}

func (x *CapabilitiesResponse) GetSupportedModels() []string {
	if x != nil {
		return x.SupportedModels
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *CapabilitiesResponse) GetLimits() *ModelLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportedRequestTypes() []string {
	if x != nil {
		return x.SupportedRequestTypes
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *CapabilitiesResponse) GetSupportsFunctionCalling() bool {
	if x != nil {
		return x.SupportsFunctionCalling
	}
	return false
}

func (x *CapabilitiesResponse) GetSupportsVision() bool {
	if x != nil {
		return x.SupportsVision
	}
	return false
}

type ModelLimits struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxTokens             int32                  `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	MaxInputLength        int32                  `protobuf:"varint,2,opt,name=max_input_length,json=maxInputLength,proto3" json:"max_input_length,omitempty"`
	MaxOutputLength       int32                  `protobuf:"varint,3,opt,name=max_output_length,json=maxOutputLength,proto3" json:"max_output_length,omitempty"`
	MaxConcurrentRequests int32                  `protobuf:"varint,4,opt,name=max_concurrent_requests,json=maxConcurrentRequests,proto3" json:"max_concurrent_requests,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ModelLimits) Reset() {
	*x = ModelLimits{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelLimits) ProtoMessage() {}

func (x *ModelLimits) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelLimits.ProtoReflect.Descriptor instead.
func (*ModelLimits) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{26}
}

func (x *ModelLimits) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelLimits) GetMaxInputLength() int32 {
	if x != nil {
		return x.MaxInputLength
	}
	return 0
}

func (x *ModelLimits) GetMaxOutputLength() int32 {
	if x != nil {
		return x.MaxOutputLength
	}
	return 0
}

func (x *ModelLimits) GetMaxConcurrentRequests() int32 {
	if x != nil {
		return x.MaxConcurrentRequests
	}
	return 0
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *structpb.Struct       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{27}
}

func (x *ValidateConfigRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP(), []int{28}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateConfigResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_specs_001_super_agent_contracts_llm_facade_proto protoreflect.FileDescriptor

const file_specs_001_super_agent_contracts_llm_facade_proto_rawDesc = "" +
	"\n" +
	"0specs/001-super-agent/contracts/llm-facade.proto\x12\x03llm\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xac\x04\n" +
	"\x11CompletionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12(\n" +
	"\bmessages\x18\x04 \x03(\v2\f.llm.MessageR\bmessages\x127\n" +
	"\fmodel_params\x18\x05 \x01(\v2\x14.llm.ModelParametersR\vmodelParams\x12<\n" +
	"\x0fensemble_config\x18\x06 \x01(\v2\x13.llm.EnsembleConfigR\x0eensembleConfig\x12'\n" +
	"\x0fmemory_enhanced\x18\a \x01(\bR\x0ememoryEnhanced\x12@\n" +
	"\bmetadata\x18\b \x03(\v2$.llm.CompletionRequest.MetadataEntryR\bmetadata\x12!\n" +
	"\frequest_type\x18\t \x01(\tR\vrequestType\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x04\n" +
	"\x12CompletionResponse\x12\x1f\n" +
	"\vresponse_id\x18\x01 \x01(\tR\n" +
	"responseId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\x12(\n" +
	"\x10response_time_ms\x18\x06 \x01(\x03R\x0eresponseTimeMs\x12#\n" +
	"\rprovider_name\x18\a \x01(\tR\fproviderName\x12#\n" +
	"\rfinish_reason\x18\b \x01(\tR\ffinishReason\x12\x1a\n" +
	"\bselected\x18\t \x01(\bR\bselected\x12'\n" +
	"\x0fselection_score\x18\n" +
	" \x01(\x01R\x0eselectionScore\x128\n" +
	"\x0ememory_sources\x18\v \x03(\v2\x11.llm.MemorySourceR\rmemorySources\x12C\n" +
	"\x11provider_metadata\x18\f \x01(\v2\x16.google.protobuf.ValueR\x10providerMetadata\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb1\x02\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12(\n" +
	"\bmessages\x18\x02 \x03(\v2\f.llm.MessageR\bmessages\x127\n" +
	"\fmodel_params\x18\x03 \x01(\v2\x14.llm.ModelParametersR\vmodelParams\x12'\n" +
	"\x0fmemory_enhanced\x18\x04 \x01(\bR\x0ememoryEnhanced\x12:\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1e.llm.ChatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x02\n" +
	"\fChatResponse\x12\x1f\n" +
	"\vresponse_id\x18\x01 \x01(\tR\n" +
	"responseId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12#\n" +
	"\rprovider_name\x18\x05 \x01(\tR\fproviderName\x12!\n" +
	"\fis_streaming\x18\x06 \x01(\bR\visStreaming\x12\x1f\n" +
	"\vis_complete\x18\a \x01(\bR\n" +
	"isComplete\x128\n" +
	"\x0ememory_sources\x18\b \x03(\v2\x11.llm.MemorySourceR\rmemorySources\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x82\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x125\n" +
	"\n" +
	"tool_calls\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\ttoolCalls\"\xea\x01\n" +
	"\x0fModelParameters\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12\x13\n" +
	"\x05top_p\x18\x04 \x01(\x01R\x04topP\x12%\n" +
	"\x0estop_sequences\x18\x05 \x03(\tR\rstopSequences\x12D\n" +
	"\x11provider_specific\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x10providerSpecific\"\x88\x02\n" +
	"\x0eEnsembleConfig\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x12#\n" +
	"\rmin_providers\x18\x02 \x01(\x05R\fminProviders\x121\n" +
	"\x14confidence_threshold\x18\x03 \x01(\x01R\x13confidenceThreshold\x12(\n" +
	"\x10fallback_to_best\x18\x04 \x01(\bR\x0efallbackToBest\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12/\n" +
	"\x13preferred_providers\x18\x06 \x03(\tR\x12preferredProviders\"\x95\x01\n" +
	"\fMemorySource\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12'\n" +
	"\x0frelevance_score\x18\x03 \x01(\x01R\x0erelevanceScore\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\"^\n" +
	"\x14ListProvidersRequest\x12!\n" +
	"\fenabled_only\x18\x01 \x01(\bR\venabledOnly\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\"H\n" +
	"\x15ListProvidersResponse\x12/\n" +
	"\tproviders\x18\x01 \x03(\v2\x11.llm.ProviderInfoR\tproviders\"\xfe\x02\n" +
	"\fProviderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12#\n" +
	"\rhealth_status\x18\a \x01(\tR\fhealthStatus\x12(\n" +
	"\x10response_time_ms\x18\b \x01(\x03R\x0eresponseTimeMs\x12!\n" +
	"\fsuccess_rate\x18\t \x01(\x01R\vsuccessRate\x12=\n" +
	"\fcapabilities\x18\n" +
	" \x01(\v2\x19.llm.CapabilitiesResponseR\fcapabilities\x12=\n" +
	"\flast_updated\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xcf\x01\n" +
	"\x12AddProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12/\n" +
	"\x06config\x18\a \x01(\v2\x17.google.protobuf.StructR\x06config\"\xe8\x01\n" +
	"\x15UpdateProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12/\n" +
	"\x06config\x18\b \x01(\v2\x17.google.protobuf.StructR\x06config\"=\n" +
	"\x15RemoveProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"u\n" +
	"\x10ProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\bprovider\x18\x03 \x01(\v2\x11.llm.ProviderInfoR\bprovider\"V\n" +
	"\rHealthRequest\x12\x1a\n" +
	"\bdetailed\x18\x01 \x01(\bR\bdetailed\x12)\n" +
	"\x10check_components\x18\x02 \x03(\tR\x0fcheckComponents\"\xb2\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x124\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x14.llm.ComponentHealthR\n" +
	"components\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xfa\x01\n" +
	"\x0fComponentHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x03R\x0eresponseTimeMs\x12;\n" +
	"\adetails\x18\x05 \x03(\v2!.llm.ComponentHealth.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x0eMetricsRequest\x12\x1d\n" +
	"\n" +
	"time_range\x18\x01 \x01(\tR\ttimeRange\x12\x18\n" +
	"\ametrics\x18\x02 \x03(\tR\ametrics\"\xb6\x01\n" +
	"\x0fMetricsResponse\x121\n" +
	"\ametrics\x18\x01 \x01(\v2\x17.google.protobuf.StructR\ametrics\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xb5\x01\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12@\n" +
	"\x0finitial_context\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x0einitialContext\x12\x1b\n" +
	"\tttl_hours\x18\x03 \x01(\x05R\bttlHours\x12%\n" +
	"\x0ememory_enabled\x18\x04 \x01(\bR\rmemoryEnabled\"[\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0finclude_context\x18\x02 \x01(\bR\x0eincludeContext\"T\n" +
	"\x17TerminateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bgraceful\x18\x02 \x01(\bR\bgraceful\"\xcf\x02\n" +
	"\x0fSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rrequest_count\x18\x05 \x01(\x05R\frequestCount\x12?\n" +
	"\rlast_activity\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x121\n" +
	"\acontext\x18\b \x01(\v2\x17.google.protobuf.StructR\acontext\"\x15\n" +
	"\x13CapabilitiesRequest\"\xe6\x02\n" +
	"\x14CapabilitiesResponse\x12)\n" +
	"\x10supported_models\x18\x01 \x03(\tR\x0fsupportedModels\x12-\n" +
	"\x12supported_features\x18\x02 \x03(\tR\x11supportedFeatures\x12(\n" +
	"\x06limits\x18\x03 \x01(\v2\x10.llm.ModelLimitsR\x06limits\x126\n" +
	"\x17supported_request_types\x18\x04 \x03(\tR\x15supportedRequestTypes\x12-\n" +
	"\x12supports_streaming\x18\x05 \x01(\bR\x11supportsStreaming\x12:\n" +
	"\x19supports_function_calling\x18\x06 \x01(\bR\x17supportsFunctionCalling\x12'\n" +
	"\x0fsupports_vision\x18\a \x01(\bR\x0esupportsVision\"\xba\x01\n" +
	"\vModelLimits\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\x05R\tmaxTokens\x12(\n" +
	"\x10max_input_length\x18\x02 \x01(\x05R\x0emaxInputLength\x12*\n" +
	"\x11max_output_length\x18\x03 \x01(\x05R\x0fmaxOutputLength\x126\n" +
	"\x17max_concurrent_requests\x18\x04 \x01(\x05R\x15maxConcurrentRequests\"H\n" +
	"\x15ValidateConfigRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\"b\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings2\x84\x06\n" +
	"\tLLMFacade\x12;\n" +
	"\bComplete\x12\x16.llm.CompletionRequest\x1a\x17.llm.CompletionResponse\x12C\n" +
	"\x0eCompleteStream\x12\x16.llm.CompletionRequest\x1a\x17.llm.CompletionResponse0\x01\x12-\n" +
	"\x04Chat\x12\x10.llm.ChatRequest\x1a\x11.llm.ChatResponse0\x01\x12F\n" +
	"\rListProviders\x12\x19.llm.ListProvidersRequest\x1a\x1a.llm.ListProvidersResponse\x12=\n" +
	"\vAddProvider\x12\x17.llm.AddProviderRequest\x1a\x15.llm.ProviderResponse\x12C\n" +
	"\x0eUpdateProvider\x12\x1a.llm.UpdateProviderRequest\x1a\x15.llm.ProviderResponse\x12C\n" +
	"\x0eRemoveProvider\x12\x1a.llm.RemoveProviderRequest\x1a\x15.llm.ProviderResponse\x126\n" +
	"\vHealthCheck\x12\x12.llm.HealthRequest\x1a\x13.llm.HealthResponse\x127\n" +
	"\n" +
	"GetMetrics\x12\x13.llm.MetricsRequest\x1a\x14.llm.MetricsResponse\x12@\n" +
	"\rCreateSession\x12\x19.llm.CreateSessionRequest\x1a\x14.llm.SessionResponse\x12:\n" +
	"\n" +
	"GetSession\x12\x16.llm.GetSessionRequest\x1a\x14.llm.SessionResponse\x12F\n" +
	"\x10TerminateSession\x12\x1c.llm.TerminateSessionRequest\x1a\x14.llm.SessionResponse2\xda\x02\n" +
	"\vLLMProvider\x12;\n" +
	"\bComplete\x12\x16.llm.CompletionRequest\x1a\x17.llm.CompletionResponse\x12C\n" +
	"\x0eCompleteStream\x12\x16.llm.CompletionRequest\x1a\x17.llm.CompletionResponse0\x01\x126\n" +
	"\vHealthCheck\x12\x12.llm.HealthRequest\x1a\x13.llm.HealthResponse\x12F\n" +
	"\x0fGetCapabilities\x12\x18.llm.CapabilitiesRequest\x1a\x19.llm.CapabilitiesResponse\x12I\n" +
	"\x0eValidateConfig\x12\x1a.llm.ValidateConfigRequest\x1a\x1b.llm.ValidateConfigResponseB\x1fZ\x1dgithub.com/superagent/pkg/apib\x06proto3"

var (
	file_specs_001_super_agent_contracts_llm_facade_proto_rawDescOnce sync.Once
	file_specs_001_super_agent_contracts_llm_facade_proto_rawDescData []byte
)

func file_specs_001_super_agent_contracts_llm_facade_proto_rawDescGZIP() []byte {
	file_specs_001_super_agent_contracts_llm_facade_proto_rawDescOnce.Do(func() {
		file_specs_001_super_agent_contracts_llm_facade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_001_super_agent_contracts_llm_facade_proto_rawDesc), len(file_specs_001_super_agent_contracts_llm_facade_proto_rawDesc)))
	})
	return file_specs_001_super_agent_contracts_llm_facade_proto_rawDescData
}

var file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_specs_001_super_agent_contracts_llm_facade_proto_goTypes = []any{
	(*CompletionRequest)(nil),       // 0: llm.CompletionRequest
	(*CompletionResponse)(nil),      // 1: llm.CompletionResponse
	(*ChatRequest)(nil),             // 2: llm.ChatRequest
	(*ChatResponse)(nil),            // 3: llm.ChatResponse
	(*Message)(nil),                 // 4: llm.Message
	(*ModelParameters)(nil),         // 5: llm.ModelParameters
	(*EnsembleConfig)(nil),          // 6: llm.EnsembleConfig
	(*MemorySource)(nil),            // 7: llm.MemorySource
	(*ListProvidersRequest)(nil),    // 8: llm.ListProvidersRequest
	(*ListProvidersResponse)(nil),   // 9: llm.ListProvidersResponse
	(*ProviderInfo)(nil),            // 10: llm.ProviderInfo
	(*AddProviderRequest)(nil),      // 11: llm.AddProviderRequest
	(*UpdateProviderRequest)(nil),   // 12: llm.UpdateProviderRequest
	(*RemoveProviderRequest)(nil),   // 13: llm.RemoveProviderRequest
	(*ProviderResponse)(nil),        // 14: llm.ProviderResponse
	(*HealthRequest)(nil),           // 15: llm.HealthRequest
	(*HealthResponse)(nil),          // 16: llm.HealthResponse
	(*ComponentHealth)(nil),         // 17: llm.ComponentHealth
	(*MetricsRequest)(nil),          // 18: llm.MetricsRequest
	(*MetricsResponse)(nil),         // 19: llm.MetricsResponse
	(*CreateSessionRequest)(nil),    // 20: llm.CreateSessionRequest
	(*GetSessionRequest)(nil),       // 21: llm.GetSessionRequest
	(*TerminateSessionRequest)(nil), // 22: llm.TerminateSessionRequest
	(*SessionResponse)(nil),         // 23: llm.SessionResponse
	(*CapabilitiesRequest)(nil),     // 24: llm.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),    // 25: llm.CapabilitiesResponse
	(*ModelLimits)(nil),             // 26: llm.ModelLimits
	(*ValidateConfigRequest)(nil),   // 27: llm.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),  // 28: llm.ValidateConfigResponse
	nil,                             // 29: llm.CompletionRequest.MetadataEntry
	nil,                             // 30: llm.ChatRequest.MetadataEntry
	nil,                             // 31: llm.ComponentHealth.DetailsEntry
	(*timestamppb.Timestamp)(nil),   // 32: google.protobuf.Timestamp
	(*structpb.Value)(nil),          // 33: google.protobuf.Value
	(*structpb.Struct)(nil),         // 34: google.protobuf.Struct
}
var file_specs_001_super_agent_contracts_llm_facade_proto_depIdxs = []int32{
	4,  // 0: llm.CompletionRequest.messages:type_name -> llm.Message
	5,  // 1: llm.CompletionRequest.model_params:type_name -> llm.ModelParameters
	6,  // 2: llm.CompletionRequest.ensemble_config:type_name -> llm.EnsembleConfig
	29, // 3: llm.CompletionRequest.metadata:type_name -> llm.CompletionRequest.MetadataEntry
	32, // 4: llm.CompletionRequest.created_at:type_name -> google.protobuf.Timestamp
	7,  // 5: llm.CompletionResponse.memory_sources:type_name -> llm.MemorySource
	33, // 6: llm.CompletionResponse.provider_metadata:type_name -> google.protobuf.Value
	32, // 7: llm.CompletionResponse.created_at:type_name -> google.protobuf.Timestamp
	4,  // 8: llm.ChatRequest.messages:type_name -> llm.Message
	5,  // 9: llm.ChatRequest.model_params:type_name -> llm.ModelParameters
	30, // 10: llm.ChatRequest.metadata:type_name -> llm.ChatRequest.MetadataEntry
	7,  // 11: llm.ChatResponse.memory_sources:type_name -> llm.MemorySource
	32, // 12: llm.ChatResponse.created_at:type_name -> google.protobuf.Timestamp
	33, // 13: llm.Message.tool_calls:type_name -> google.protobuf.Value
	34, // 14: llm.ModelParameters.provider_specific:type_name -> google.protobuf.Struct
	10, // 15: llm.ListProvidersResponse.providers:type_name -> llm.ProviderInfo
	25, // 16: llm.ProviderInfo.capabilities:type_name -> llm.CapabilitiesResponse
	32, // 17: llm.ProviderInfo.last_updated:type_name -> google.protobuf.Timestamp
	34, // 18: llm.AddProviderRequest.config:type_name -> google.protobuf.Struct
	34, // 19: llm.UpdateProviderRequest.config:type_name -> google.protobuf.Struct
	10, // 20: llm.ProviderResponse.provider:type_name -> llm.ProviderInfo
	17, // 21: llm.HealthResponse.components:type_name -> llm.ComponentHealth
	32, // 22: llm.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	31, // 23: llm.ComponentHealth.details:type_name -> llm.ComponentHealth.DetailsEntry
	34, // 24: llm.MetricsResponse.metrics:type_name -> google.protobuf.Struct
	32, // 25: llm.MetricsResponse.start_time:type_name -> google.protobuf.Timestamp
	32, // 26: llm.MetricsResponse.end_time:type_name -> google.protobuf.Timestamp
	34, // 27: llm.CreateSessionRequest.initial_context:type_name -> google.protobuf.Struct
	32, // 28: llm.SessionResponse.last_activity:type_name -> google.protobuf.Timestamp
	32, // 29: llm.SessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	34, // 30: llm.SessionResponse.context:type_name -> google.protobuf.Struct
	26, // 31: llm.CapabilitiesResponse.limits:type_name -> llm.ModelLimits
	34, // 32: llm.ValidateConfigRequest.config:type_name -> google.protobuf.Struct
	0,  // 33: llm.LLMFacade.Complete:input_type -> llm.CompletionRequest
	0,  // 34: llm.LLMFacade.CompleteStream:input_type -> llm.CompletionRequest
	2,  // 35: llm.LLMFacade.Chat:input_type -> llm.ChatRequest
	8,  // 36: llm.LLMFacade.ListProviders:input_type -> llm.ListProvidersRequest
	11, // 37: llm.LLMFacade.AddProvider:input_type -> llm.AddProviderRequest
	12, // 38: llm.LLMFacade.UpdateProvider:input_type -> llm.UpdateProviderRequest
	13, // 39: llm.LLMFacade.RemoveProvider:input_type -> llm.RemoveProviderRequest
	15, // 40: llm.LLMFacade.HealthCheck:input_type -> llm.HealthRequest
	18, // 41: llm.LLMFacade.GetMetrics:input_type -> llm.MetricsRequest
	20, // 42: llm.LLMFacade.CreateSession:input_type -> llm.CreateSessionRequest
	21, // 43: llm.LLMFacade.GetSession:input_type -> llm.GetSessionRequest
	22, // 44: llm.LLMFacade.TerminateSession:input_type -> llm.TerminateSessionRequest
	0,  // 45: llm.LLMProvider.Complete:input_type -> llm.CompletionRequest
	0,  // 46: llm.LLMProvider.CompleteStream:input_type -> llm.CompletionRequest
	15, // 47: llm.LLMProvider.HealthCheck:input_type -> llm.HealthRequest
	24, // 48: llm.LLMProvider.GetCapabilities:input_type -> llm.CapabilitiesRequest
	27, // 49: llm.LLMProvider.ValidateConfig:input_type -> llm.ValidateConfigRequest
	1,  // 50: llm.LLMFacade.Complete:output_type -> llm.CompletionResponse
	1,  // 51: llm.LLMFacade.CompleteStream:output_type -> llm.CompletionResponse
	3,  // 52: llm.LLMFacade.Chat:output_type -> llm.ChatResponse
	9,  // 53: llm.LLMFacade.ListProviders:output_type -> llm.ListProvidersResponse
	14, // 54: llm.LLMFacade.AddProvider:output_type -> llm.ProviderResponse
	14, // 55: llm.LLMFacade.UpdateProvider:output_type -> llm.ProviderResponse
	14, // 56: llm.LLMFacade.RemoveProvider:output_type -> llm.ProviderResponse
	16, // 57: llm.LLMFacade.HealthCheck:output_type -> llm.HealthResponse
	19, // 58: llm.LLMFacade.GetMetrics:output_type -> llm.MetricsResponse
	23, // 59: llm.LLMFacade.CreateSession:output_type -> llm.SessionResponse
	23, // 60: llm.LLMFacade.GetSession:output_type -> llm.SessionResponse
	23, // 61: llm.LLMFacade.TerminateSession:output_type -> llm.SessionResponse
	1,  // 62: llm.LLMProvider.Complete:output_type -> llm.CompletionResponse
	1,  // 63: llm.LLMProvider.CompleteStream:output_type -> llm.CompletionResponse
	16, // 64: llm.LLMProvider.HealthCheck:output_type -> llm.HealthResponse
	25, // 65: llm.LLMProvider.GetCapabilities:output_type -> llm.CapabilitiesResponse
	28, // 66: llm.LLMProvider.ValidateConfig:output_type -> llm.ValidateConfigResponse
	50, // [50:67] is the sub-list for method output_type
	33, // [33:50] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_specs_001_super_agent_contracts_llm_facade_proto_init() }
func file_specs_001_super_agent_contracts_llm_facade_proto_init() {
	if File_specs_001_super_agent_contracts_llm_facade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_001_super_agent_contracts_llm_facade_proto_rawDesc), len(file_specs_001_super_agent_contracts_llm_facade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_specs_001_super_agent_contracts_llm_facade_proto_goTypes,
		DependencyIndexes: file_specs_001_super_agent_contracts_llm_facade_proto_depIdxs,
		MessageInfos:      file_specs_001_super_agent_contracts_llm_facade_proto_msgTypes,
	}.Build()
	File_specs_001_super_agent_contracts_llm_facade_proto = out.File
	file_specs_001_super_agent_contracts_llm_facade_proto_goTypes = nil
	file_specs_001_super_agent_contracts_llm_facade_proto_depIdxs = nil
}
