// Package cody provides Sourcegraph Cody agent integration.
// Cody: AI coding assistant with codebase intelligence.
package cody

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// Cody provides Sourcegraph Cody integration
type Cody struct {
	*base.BaseIntegration
	config   *Config
	snippets []Snippet
}

// Config holds Cody configuration
type Config struct {
	base.BaseConfig
	SourcegraphURL string
	AccessToken    string
	Model          string
}

// Snippet represents a code snippet
type Snippet struct {
	ID          string `json:"id"`
	Content     string `json:"content"`
	File        string `json:"file"`
	Language    string `json:"language"`
	Description string `json:"description"`
}

// New creates a new Cody integration
func New() *Cody {
	info := agents.AgentInfo{
		Type:        agents.TypeCody,
		Name:        "Cody",
		Description: "AI coding assistant with codebase intelligence",
		Vendor:      "Sourcegraph",
		Version:     "1.0.0",
		Capabilities: []string{
			"code_intelligence",
			"codebase_search",
			"chat",
			"code_explanation",
			"code_generation",
			"code_review",
			"symbol_search",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &Cody{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			SourcegraphURL: "https://sourcegraph.com",
			Model:          "anthropic/claude-3-sonnet",
		},
		snippets: make([]Snippet, 0),
	}
}

// Initialize initializes Cody
func (c *Cody) Initialize(ctx context.Context, config interface{}) error {
	if err := c.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		c.config = cfg
	}
	
	return c.loadSnippets()
}

// loadSnippets loads code snippets
func (c *Cody) loadSnippets() error {
	snippetsPath := filepath.Join(c.GetWorkDir(), "snippets.json")
	
	if _, err := os.Stat(snippetsPath); os.IsNotExist(err) {
		return nil
	}
	
	data, err := os.ReadFile(snippetsPath)
	if err != nil {
		return fmt.Errorf("read snippets: %w", err)
	}
	
	return json.Unmarshal(data, &c.snippets)
}

// saveSnippets saves code snippets
func (c *Cody) saveSnippets() error {
	snippetsPath := filepath.Join(c.GetWorkDir(), "snippets.json")
	data, err := json.MarshalIndent(c.snippets, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal snippets: %w", err)
	}
	return os.WriteFile(snippetsPath, data, 0644)
}

// Execute executes a command
func (c *Cody) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !c.IsStarted() {
		if err := c.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "chat":
		return c.chat(ctx, params)
	case "explain":
		return c.explain(ctx, params)
	case "generate":
		return c.generate(ctx, params)
	case "search":
		return c.search(ctx, params)
	case "review":
		return c.review(ctx, params)
	case "edit":
		return c.edit(ctx, params)
	case "symbol":
		return c.symbol(ctx, params)
	case "save_snippet":
		return c.saveSnippet(ctx, params)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// chat performs chat with Cody
func (c *Cody) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	context, _ := params["context"].(string)
	
	return map[string]interface{}{
		"message":  message,
		"context":  context,
		"response": fmt.Sprintf("Cody: %s", message),
		"model":    c.config.Model,
	}, nil
}

// explain explains code
func (c *Cody) explain(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	if code == "" {
		return nil, fmt.Errorf("code required")
	}
	
	return map[string]interface{}{
		"code":        code,
		"explanation": fmt.Sprintf("This code %s...", c.summarizeCode(code)),
		"model":       c.config.Model,
	}, nil
}

// generate generates code
func (c *Cody) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	language, _ := params["language"].(string)
	
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	if language == "" {
		language = "go"
	}
	
	code := fmt.Sprintf("// Generated by Cody\n// Prompt: %s\n\nfunc generated() {\n    // Implementation\n}\n", prompt)
	
	return map[string]interface{}{
		"prompt":   prompt,
		"language": language,
		"code":     code,
		"model":    c.config.Model,
	}, nil
}

// search searches codebase
func (c *Cody) search(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	query, _ := params["query"].(string)
	if query == "" {
		return nil, fmt.Errorf("query required")
	}
	
	results := []map[string]interface{}{
		{"file": "main.go", "line": 10, "content": "func main()"},
		{"file": "utils.go", "line": 5, "content": "func helper()"},
	}
	
	return map[string]interface{}{
		"query":   query,
		"results": results,
		"count":   len(results),
	}, nil
}

// review reviews code
func (c *Cody) review(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	if code == "" {
		return nil, fmt.Errorf("code required")
	}
	
	issues := []map[string]interface{}{
		{"severity": "info", "message": "Consider adding comments"},
		{"severity": "warning", "message": "Function is quite long"},
	}
	
	return map[string]interface{}{
		"code":   code,
		"issues": issues,
		"count":  len(issues),
	}, nil
}

// edit edits code
func (c *Cody) edit(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	file, _ := params["file"].(string)
	instruction, _ := params["instruction"].(string)
	
	if file == "" || instruction == "" {
		return nil, fmt.Errorf("file and instruction required")
	}
	
	return map[string]interface{}{
		"file":        file,
		"instruction": instruction,
		"changes":     []string{"Applied edits"},
	}, nil
}

// symbol searches for symbol
func (c *Cody) symbol(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	name, _ := params["name"].(string)
	if name == "" {
		return nil, fmt.Errorf("name required")
	}
	
	return map[string]interface{}{
		"symbol": name,
		"definitions": []map[string]interface{}{
			{"file": "main.go", "line": 15, "type": "function"},
		},
		"references": []map[string]interface{}{
			{"file": "utils.go", "line": 20},
		},
	}, nil
}

// saveSnippet saves a code snippet
func (c *Cody) saveSnippet(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	content, _ := params["content"].(string)
	description, _ := params["description"].(string)
	language, _ := params["language"].(string)
	
	if content == "" {
		return nil, fmt.Errorf("content required")
	}
	
	snippet := Snippet{
		ID:          fmt.Sprintf("snippet-%d", len(c.snippets)+1),
		Content:     content,
		Description: description,
		Language:    language,
	}
	
	c.snippets = append(c.snippets, snippet)
	
	if err := c.saveSnippets(); err != nil {
		return nil, err
	}
	
	return map[string]interface{}{
		"snippet": snippet,
		"status":  "saved",
	}, nil
}

// summarizeCode summarizes code
func (c *Cody) summarizeCode(code string) string {
	lines := strings.Split(code, "\n")
	if len(lines) > 3 {
		return strings.Join(lines[:3], " ") + "..."
	}
	return code
}

// IsAvailable checks availability
func (c *Cody) IsAvailable() bool {
	return c.config.AccessToken != ""
}

var _ agents.AgentIntegration = (*Cody)(nil)