// Package deepseek provides DeepSeek CLI agent integration.
// DeepSeek: High-performance code intelligence model.
package deepseek

import (
	"context"
	"fmt"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// DeepSeek provides DeepSeek integration
type DeepSeek struct {
	*base.BaseIntegration
	config *Config
}

// Config holds DeepSeek configuration
type Config struct {
	base.BaseConfig
	APIKey      string
	Model       string
	MaxTokens   int
	Temperature float64
}

// New creates a new DeepSeek integration
func New() *DeepSeek {
	info := agents.AgentInfo{
		Type:        agents.TypeDeepSeek,
		Name:        "DeepSeek",
		Description: "High-performance code intelligence",
		Vendor:      "DeepSeek",
		Version:     "1.0.0",
		Capabilities: []string{
			"code_generation",
			"code_completion",
			"code_explanation",
			"chat",
			"reasoning",
		},
		IsEnabled: true,
		Priority:  2,
	}
	
	return &DeepSeek{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			Model:       "deepseek-coder-v3",
			MaxTokens:   8192,
			Temperature: 0.7,
		},
	}
}

// Initialize initializes DeepSeek
func (d *DeepSeek) Initialize(ctx context.Context, config interface{}) error {
	if err := d.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}
	
	if cfg, ok := config.(*Config); ok {
		d.config = cfg
	}
	
	return nil
}

// Execute executes a command
func (d *DeepSeek) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !d.IsStarted() {
		if err := d.Start(ctx); err != nil {
			return nil, err
		}
	}
	
	switch command {
	case "chat":
		return d.chat(ctx, params)
	case "generate":
		return d.generate(ctx, params)
	case "complete":
		return d.complete(ctx, params)
	case "explain":
		return d.explain(ctx, params)
	case "status":
		return d.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// chat performs chat
func (d *DeepSeek) chat(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	message, _ := params["message"].(string)
	if message == "" {
		return nil, fmt.Errorf("message required")
	}
	
	return map[string]interface{}{
		"message":  message,
		"response": fmt.Sprintf("DeepSeek: %s", message),
		"model":    d.config.Model,
	}, nil
}

// generate generates code
func (d *DeepSeek) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prompt, _ := params["prompt"].(string)
	language, _ := params["language"].(string)
	
	if prompt == "" {
		return nil, fmt.Errorf("prompt required")
	}
	
	if language == "" {
		language = "go"
	}
	
	code := fmt.Sprintf("// Generated by DeepSeek\n// Model: %s\n// Prompt: %s\n\nfunc generated() {\n    // Implementation\n}\n", d.config.Model, prompt)
	
	return map[string]interface{}{
		"prompt":   prompt,
		"language": language,
		"code":     code,
		"model":    d.config.Model,
	}, nil
}

// complete generates completion
func (d *DeepSeek) complete(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	prefix, _ := params["prefix"].(string)
	suffix, _ := params["suffix"].(string)
	
	return map[string]interface{}{
		"prefix":     prefix,
		"suffix":     suffix,
		"completion": "// DeepSeek completion",
		"model":      d.config.Model,
	}, nil
}

// explain explains code
func (d *DeepSeek) explain(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	code, _ := params["code"].(string)
	if code == "" {
		return nil, fmt.Errorf("code required")
	}
	
	return map[string]interface{}{
		"code":        code,
		"explanation": "Code explanation by DeepSeek",
		"model":       d.config.Model,
	}, nil
}

// status returns status
func (d *DeepSeek) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available":   d.IsAvailable(),
		"model":       d.config.Model,
		"max_tokens":  d.config.MaxTokens,
	}, nil
}

// IsAvailable checks availability
func (d *DeepSeek) IsAvailable() bool {
	return d.config.APIKey != ""
}

var _ agents.AgentIntegration = (*DeepSeek)(nil)